
export const Type ={

  LEVEL_SET: 'LEVEL_SET',
  // LEVEL_FINISHED: 'LEVEL_FINISHED',

  MODAL_OPEN: 'MODAL_OPEN',
  MODAL_CLOSE: 'MODAL_CLOSE',

  LOCALIZATION: 'LOCALIZATION',

  WALLS_SET: 'WALLS_SET',
  WALLS_GROWTH: 'WALLS_GROWTH',
  WALLS_DESTROY_HUMMER: 'WALLS_DESTROY_HUMMER',
  WALLS_DESTROY_ROCKET: 'WALLS_DESTROY_ROCKET',
  WALLS_DESTROY_DYNAMITE: 'WALLS_DESTROY_DYNAMITE',
  WALLS_DESTROY_TRAMP: 'WALLS_DESTROY_TRAMP',

  WALLS_REACTION_DESTROY: 'WALLS_REACTION_DESTROY',
  WALLS_REACTION_CLEAL: 'WALLS_REACTION_CLEAL',

  MONSTER_SET_CELL: 'MONSTER_SET_CELL',
  MONSTER_MOVE: 'MONSTER_MOVE',
  MONSTER_CHARGE_SKILL: 'MONSTER_CHARGE_SKILL',
  MONSTER_RECHARGE_SKILL: 'MONSTER_RECHARGE_SKILL',
  MONSTER_SKILL_ACTIVATE: 'MONSTER_SKILL_ACTIVATE',
  MONSTER_SKILL_DEACTIVATE: 'MONSTER_SKILL_DEACTIVATE',
  MONSTER_SKILLS_DEACTIVATE: 'MONSTER_SKILLS_DEACTIVATE',
  MONSTER_CHOOSE: 'MONSTER_CHOOSE',
  MONSTER_EXP_UP: 'MONSTER_EXP_UP',
  MONSTER_INIT: 'MONSTER_INIT',
  MONSTER_UPLOAD: 'MONSTER_UPLOAD',

  MONSTERS_DEACTIVATE: 'MONSTERS_DEACTIVATE',
  MONSTERS_ADD_ACTIVE: 'MONSTERS_ADD_ACTIVE',
  MONSTERS_UPLOAD: 'MONSTERS_UPLOAD',
  MONSTERS_INIT: 'MONSTERS_INIT',

  EXIT_SET: 'EXIT_SET',

  MISSIONS_UPLOAD: 'MISSIONS_UPLOAD',
  MISSIONS_OPEN: 'MISSIONS_OPEN',

  EXPERIENCE_UP: 'EXPERIENCE_UP',
  EXPERIENCE_DOWN: 'EXPERIENCE_DOWN',
};
